### ISSUE TITLE
Build for the most GOOS/GOARCH pairs break with avfs in dependencies.

### ISSUE THREAD

**Issue by SCP002** [avfs/avfs#4]
The only binaries which built without errors were for:
* Linux AMD64
* Linux s390x
* Windows AMD64

Trimmed version of gox (cross-compile tool) log is under the spoiler:

<details>
<summary><b>Click me</b></summary>

linux/arm

* avfs@v0.28.0\vfs\memfs\memfs_file.go:168:17: cannot convert math.MaxUint64 (untyped int constant 18446744073709551615) to type uintptr
* avfs@v0.28.0\vfs\osfs\osfs_linux.go:145:9: cannot use lst.Sys.Nlink (variable of type uint32) as type uint64 in return statement

---
linux/mipsle

* avfs@v0.28.0\vfs\memfs\memfs_file.go:168:17: cannot convert math.MaxUint64 (untyped int constant 18446744073709551615) to type uintptr
* avfs@v0.28.0\vfs\osfs\osfs_linux.go:145:9: cannot use lst.Sys.Nlink (variable of type uint32) as type uint64 in return statement

---
openbsd/386

* avfs@v0.28.0\umask.go:30:2: undefined: SetUMask

---
linux/386

* avfs@v0.28.0\vfs\osfs\osfs_linux.go:145:9: cannot use lst.Sys.Nlink (variable of type uint32) as type uint64 in return statement
* avfs@v0.28.0\vfs\memfs\memfs_file.go:168:17: cannot convert math.MaxUint64 (untyped int constant 18446744073709551615) to type uintptr

---
freebsd/amd64

* avfs@v0.28.0\umask.go:30:2: undefined: SetUMask

---
freebsd/386

* avfs@v0.28.0\umask.go:30:2: undefined: SetUMask

---
openbsd/amd64

* avfs@v0.28.0\umask.go:30:2: undefined: SetUMask

---
windows/386

* avfs@v0.28.0\vfs\memfs\memfs_file.go:168:17: cannot convert math.MaxUint64 (untyped int constant 18446744073709551615) to type uintptr

---
netbsd/arm

* avfs@v0.28.0\umask.go:30:2: undefined: SetUMask

---
freebsd/arm

* avfs@v0.28.0\umask.go:30:2: undefined: SetUMask

---
linux/mips64

* avfs@v0.28.0\vfs\osfs\osfs_linux.go:145:9: cannot use lst.Sys.Nlink (variable of type uint32) as type uint64 in return statement

---
netbsd/386

* avfs@v0.28.0\umask.go:30:2: undefined: SetUMask

---
linux/mips64le

* avfs@v0.28.0\vfs\osfs\osfs_linux.go:145:9: cannot use lst.Sys.Nlink (variable of type uint32) as type uint64 in return statement

---
linux/mips

* avfs@v0.28.0\vfs\memfs\memfs_file.go:168:17: cannot convert math.MaxUint64 (untyped int constant 18446744073709551615) to type uintptr
* avfs@v0.28.0\vfs\osfs\osfs_linux.go:145:9: cannot use lst.Sys.Nlink (variable of type uint32) as type uint64 in return statement

---
netbsd/amd64

* avfs@v0.28.0\umask.go:30:2: undefined: SetUMask

---
darwin/amd64

* avfs@v0.28.0\umask.go:30:2: undefined: SetUMask
</details>

**Comment by psadac** [comment]
Thank you @SCP002  for this bug report, I have already fixed some bugs and will add somme build tests using gox (which I didn't know by the way).

**Comment by SCP002** [comment]
With v0.30.0 the project with avfs dependencies builds successfully, gox does not complain, feel free to re-open this if you wish and thank you both for your work & time. This library saved me a lot of time ❤️
