### ISSUE TITLE
Stat and ErrNotExist are broken

### ISSUE THREAD

**Issue by Fyb3roptik** [avfs/avfs#5]
OS: Macos and Ubuntu

```go
_, err = vfs.Stat(filepath.Dir(path))
errors.Is(err, fs.ErrNotExist)
```

errors.Is is returning FALSE even though I am getting this in the log:

```
stat /tmp/MBI59I8R4FK0728DOHS1: no such file or directory
```

**Comment by psadac** [comment]
> OS: Macos and Ubuntu
Macos is not supported but some file systems should be ok.

> errors.Is is returning FALSE even though I am getting this in the log:
which vfs are you using ? could you provide a complete example ?

**Comment by Fyb3roptik** [comment]
It looks like using `avfs.ErrNoSuchFileOrDir` is working for that

**Comment by Fyb3roptik** [comment]
Which OS's are supported?
