### ISSUE TITLE
Feature Request: FailFS

### ISSUE THREAD

**Issue by 0xDEC0DE** [avfs/avfs#8]
The `MemFS` is great for unit tests, and I absolutely adore your implementation.  But it does present challenges when attempting to test failure modes, since it, you know, works really well.

I was able to achieve limited success testing failure-to-write scenarios by loading an `RoFS` view over the `MemFS` and running tests, and I thought perhaps there would be utility in taking that idea further.

So I came up with this for my tests:

https://github.com/retr0h/gilt/commit/6293c13982a204f5464b7a0f114961c26d2d8566

...and some snippets of how it is implemented/used:

https://github.com/retr0h/gilt/commit/52f0ddaa862cc5d709d5f225f1134a26c70bbd55

It's fidgety, cantankerous, and prone to panics if you don't set it up right, but there might be the precursor to something useful if left in more capable hands.

Would this be worth developing further?

**Comment by psadac** [comment]
Your idea and your implementation is very clever, but it's too panicky for my taste. So I have implemented a much dumber one, probably less panic friendly, which only necessitates only one function to generate failures. However I am not sure it will work for you.

**Comment by 0xDEC0DE** [comment]
It appears to work mostly the same, and in a few cases better, since it supports "fall-through" behavior.

Some docs on how to use it might be nice, though.

See: https://github.com/retr0h/gilt/pull/238
